$(info $(lastword $(MAKEFILE_LIST)))

# Components that need to be build aside from this one and will be linked later
# COMPONENTS =

# Components that need to be build first because the current component uses the
# files generated by the dependency
DEPENDENCIES := b
